---
title: "Untitled"
author: "Steve Simon"
date: "8/11/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5675733/

```{r}
x <- c(
  2.9,
  1.1,
  1.1,
  1.6,
  6.6, 7.6,
  1,
  4,
  2,
  2.2,
  1.6, 2.9,
  4.2,
  1.7,
  1,
  1.5, 1.8, 
  3.4,
  0.3, 0.5, 0.8,
  0.38,
  0.96,
  1.6,
  1.5, 1.9, 
  1.0, 2.3, 5.9,
  1.5,
  3.7,
  5.3,
  0.5,
  1.5,
  1.3, 2.4,
  1.1,
  2.1,
  1,
  2.8,
  5,
  4.3, 5.5,
  4.5,
  1.8,
  2.9,
  0.39,
  1.9)
g <- c(
  1,
  2,
  3,
  4,
  5, 5,
  6,
  7,
  8,
  9,
  10, 10,
  11,
  12,
  13,
  14, 14, 
  15,
  16, 16, 16,
  17,
  18,
  19,
  20, 20, 
  21, 21, 21,
  22,
  23,
  24,
  25,
  26,
  27, 27,
  28,
  29,
  30,
  31,
  32,
  33, 33,
  34,
  35,
  36,
  37,
  38)
length(g)
length(x)
mean(log(x))
exp(mean(log(x)))
sd(log(x))
exp(sd(log(x)))
mean(x)
sd(x)
100*sd(x)/ mean(x)
summary(lm(log(x)~factor(g)))
library(lme4)
lmer(log(x)~(1|factor(g)))
exp(0.6031+c(-1.96, 1.96)*0.7580851/sqrt(200))
power.t.test(n=200, sd=0.4791, delta=log(1.25))
power.t.test(n=200, sd=0.758, delta=log(1.25))
```
