---
title: "Sample markdown code for PowerPoint presentations"
author: "Steve Simon"
date: "Created 2022-10-15"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
output:
  powerpoint_presentation:
    reference_doc: wide-screen-template.pptx
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo=FALSE,
  message=FALSE,
  warning=FALSE)
suppressMessages(
  suppressWarnings(
    library(tidyverse)
  )
)
suppressMessages(
  suppressWarnings(
    library(rpart)
  )
)
# Width and height of all graphs
w=6
h=3
```

### Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

### Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

### Slide with Plot

```{r pressure, echo=FALSE}
plot(pressure)
```

### test

```{r}
plot(1:4, 2:5)
```

### Column format

:::::: {.columns}
::: {.column}
Content of the left column.

```{r}
rnorm(10)
```
:::

::: {.column}
Content of the right column.

```{r, echo=FALSE}
plot(1:4, 2:5)
```

:::
::::::